credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: $2b$12$b6eitYPiqNb8xAoHGy2Io.k5aJPGbKPPK0lFmLVKhAMTggeNaoYGC # Ceci est un exemple de mot de passe haché
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - admin@example.com